//! Compiles the About window's credits (`contributors/*.tsv` at the workspace root) into static
//! tables (`$OUT_DIR/credits_tables.rs`, included by `src/credits.rs`). No network. A missing or
//! malformed file gives an empty table and a `cargo::warning`, never a failed build. Names and
//! emails from `people.tsv` are compiled in only for rows with `consent` = `yes`.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[path = "src/credits_data.rs"]
#[allow(dead_code)]
mod credits_data;

fn read(dir: &Path, file: &str) -> String {
    let path = dir.join(file);
    println!("cargo::rerun-if-changed={}", path.display());
    match std::fs::read_to_string(&path) {
        Ok(s) => s,
        Err(e) => {
            println!("cargo::warning=contributors/{file}: {e}; the About window's table will be empty");
            String::new()
        }
    }
}

fn parsed<'a, T>(file: &str, text: &'a str, parse: fn(&'a str) -> Result<Vec<T>, String>) -> Vec<T> {
    if text.is_empty() {
        return Vec::new();
    }
    parse(text).unwrap_or_else(|e| {
        println!("cargo::warning=contributors/{file} is malformed ({e}); the About window's table will be empty");
        Vec::new()
    })
}

fn main() {
    println!("cargo::rerun-if-changed=src/credits_data.rs");
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default());
    let dir = manifest.join("../../contributors");
    let (c, p, m, h) = (read(&dir, "commits.tsv"), read(&dir, "prs.tsv"), read(&dir, "models.tsv"), read(&dir, "people.tsv"));
    let commits = parsed("commits.tsv", &c, credits_data::parse_commits);
    let prs = parsed("prs.tsv", &p, credits_data::parse_prs);
    let models = parsed("models.tsv", &m, credits_data::parse_models);
    let people = parsed("people.tsv", &h, credits_data::parse_people);

    let mut s = String::from("// @generated by build.rs from contributors/*.tsv\n");
    s.push_str("pub static COMMITS: &[Commit<'static>] = &[\n");
    for r in &commits {
        let _ = writeln!(
            s,
            "Commit{{sha:{:?},url:{:?},login:{:?},date:{:?},additions:{},deletions:{},pr:{:?},models:{:?}}},",
            r.sha, r.url, r.login, r.date, r.additions, r.deletions, r.pr, r.models
        );
    }
    s.push_str("];\npub static PRS: &[Pr<'static>] = &[\n");
    for r in &prs {
        let _ = writeln!(
            s,
            "Pr{{number:{},url:{:?},login:{:?},merged_at:{:?},additions:{},deletions:{},commits:{},models:{:?}}},",
            r.number, r.url, r.login, r.merged_at, r.additions, r.deletions, r.commits, r.models
        );
    }
    s.push_str("];\npub static MODELS: &[Model<'static>] = &[\n");
    for r in &models {
        let _ = writeln!(s, "Model{{id:{:?},company:{:?},model:{:?},version:{:?},trailer:{:?}}},", r.id, r.company, r.model, r.version, r.trailer);
    }
    s.push_str("];\npub static PEOPLE: &[Person<'static>] = &[\n");
    for r in &people {
        // Without consent nothing but the login (public anyway) is compiled in.
        let (display, real, email) = if r.consent { (r.display_name, r.real_name, r.email) } else { ("", "", "") };
        let _ = writeln!(
            s,
            "Person{{login:{:?},consent:{},consent_date:{:?},consent_source:{:?},display_name:{:?},real_name:{:?},email:{:?}}},",
            r.login, r.consent, r.consent_date, r.consent_source, display, real, email
        );
    }
    s.push_str("];\n");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap_or_default()).join("credits_tables.rs");
    if let Err(e) = std::fs::write(&out, s) {
        println!("cargo::warning=could not write {}: {e}", out.display());
    }
}
